# Generated by Django 5.1.6 on 2025-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descreption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
