# Generated by Django 5.1.5 on 2025-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descreption', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
